Revert "Add OpenLinuxBoot.efi and ext4_x64.efi"
It's good that new entry which is "Ubuntu 24.04 LTS" shows up.
But, the old entry which is "NO NAME" still appears and "NO NAME"
still shows the the below errors:

Could not read \EFI\: Invalid Parameter
Error: could not find boot options: Invalid Parameter
start_image() returned Invalid Parameter
OC: Boot failed - Invalid Parameter
OCB: StartImage failed - Invalid Parameter

This reverts commit ef5869c7d9144a20f3a32a9372bae8488f20eaff.